/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models

import com.neaniesoft.warami.api.models.AdminPurgeCommunity
import com.neaniesoft.warami.api.models.Person

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param adminPurgeCommunity 
 * @param admin 
 */
@JsonClass(generateAdapter = true)

data class AdminPurgeCommunityView (

    @Json(name = "admin_purge_community")
    val adminPurgeCommunity: AdminPurgeCommunity,

    @Json(name = "admin")
    val admin: Person? = null

)

