/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models

import com.neaniesoft.warami.api.models.AdminPurgePost
import com.neaniesoft.warami.api.models.Community
import com.neaniesoft.warami.api.models.Person

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param adminPurgePost 
 * @param community 
 * @param admin 
 */
@JsonClass(generateAdapter = true)

data class AdminPurgePostView (

    @Json(name = "admin_purge_post")
    val adminPurgePost: AdminPurgePost,

    @Json(name = "community")
    val community: Community,

    @Json(name = "admin")
    val admin: Person? = null

)

