/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models

import com.neaniesoft.warami.api.models.PersonView

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param personView 
 * @param banned 
 */
@JsonClass(generateAdapter = true)

data class BanFromCommunityResponse (

    @Json(name = "person_view")
    val personView: PersonView,

    @Json(name = "banned")
    val banned: kotlin.Boolean

)

