/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param communityId 
 * @param auth 
 */
@JsonClass(generateAdapter = true)

data class BlockCommunity (

    @Json(name = "community_id")
    val communityId: java.math.BigDecimal,

    @Json(name = "auth")
    val auth: kotlin.String

)

