/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param newPassword 
 * @param newPasswordVerify 
 * @param oldPassword 
 * @param auth 
 */
@JsonClass(generateAdapter = true)

data class ChangePassword (

    @Json(name = "new_password")
    val newPassword: kotlin.String,

    @Json(name = "new_password_verify")
    val newPasswordVerify: kotlin.String,

    @Json(name = "old_password")
    val oldPassword: kotlin.String,

    @Json(name = "auth")
    val auth: kotlin.String

)

