/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param creatorId 
 * @param postId 
 * @param content 
 * @param removed 
 * @param published 
 * @param deleted 
 * @param apId 
 * @param local 
 * @param path 
 * @param distinguished 
 * @param languageId 
 * @param updated 
 */
@JsonClass(generateAdapter = true)

data class Comment (

    @Json(name = "id")
    val id: java.math.BigDecimal,

    @Json(name = "creator_id")
    val creatorId: java.math.BigDecimal,

    @Json(name = "post_id")
    val postId: java.math.BigDecimal,

    @Json(name = "content")
    val content: kotlin.String,

    @Json(name = "removed")
    val removed: kotlin.Boolean,

    @Json(name = "published")
    val published: kotlin.String,

    @Json(name = "deleted")
    val deleted: kotlin.Boolean,

    @Json(name = "ap_id")
    val apId: kotlin.String,

    @Json(name = "local")
    val local: kotlin.Boolean,

    @Json(name = "path")
    val path: kotlin.String,

    @Json(name = "distinguished")
    val distinguished: kotlin.Boolean,

    @Json(name = "language_id")
    val languageId: java.math.BigDecimal,

    @Json(name = "updated")
    val updated: kotlin.String? = null

)

