/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models

import com.neaniesoft.warami.api.models.Comment
import com.neaniesoft.warami.api.models.CommentAggregates
import com.neaniesoft.warami.api.models.Community
import com.neaniesoft.warami.api.models.Person
import com.neaniesoft.warami.api.models.Post

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param comment 
 * @param creator 
 * @param post 
 * @param community 
 * @param counts 
 * @param myVote 
 */
@JsonClass(generateAdapter = true)

data class CommentView (

    @Json(name = "comment")
    val comment: Comment,

    @Json(name = "creator")
    val creator: Person,

    @Json(name = "post")
    val post: Post,

    @Json(name = "community")
    val community: Community,

    @Json(name = "counts")
    val counts: CommentAggregates,

    @Json(name = "my_vote")
    val myVote: java.math.BigDecimal? = null

)

