/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param commentId 
 * @param score 
 * @param upvotes 
 * @param downvotes 
 * @param published 
 * @param childCount 
 * @param hotRank 
 */
@JsonClass(generateAdapter = true)

data class CommentAggregates (

    @Json(name = "id")
    val id: java.math.BigDecimal,

    @Json(name = "comment_id")
    val commentId: java.math.BigDecimal,

    @Json(name = "score")
    val score: java.math.BigDecimal,

    @Json(name = "upvotes")
    val upvotes: java.math.BigDecimal,

    @Json(name = "downvotes")
    val downvotes: java.math.BigDecimal,

    @Json(name = "published")
    val published: kotlin.String,

    @Json(name = "child_count")
    val childCount: java.math.BigDecimal,

    @Json(name = "hot_rank")
    val hotRank: java.math.BigDecimal

)

