/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param name 
 * @param title 
 * @param removed 
 * @param published 
 * @param deleted 
 * @param nsfw 
 * @param actorId 
 * @param local 
 * @param hidden 
 * @param postingRestrictedToMods 
 * @param instanceId 
 * @param description 
 * @param updated 
 * @param icon 
 * @param banner 
 */
@JsonClass(generateAdapter = true)

data class Community (

    @Json(name = "id")
    val id: java.math.BigDecimal,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "removed")
    val removed: kotlin.Boolean,

    @Json(name = "published")
    val published: kotlin.String,

    @Json(name = "deleted")
    val deleted: kotlin.Boolean,

    @Json(name = "nsfw")
    val nsfw: kotlin.Boolean,

    @Json(name = "actor_id")
    val actorId: kotlin.String,

    @Json(name = "local")
    val local: kotlin.Boolean,

    @Json(name = "hidden")
    val hidden: kotlin.Boolean,

    @Json(name = "posting_restricted_to_mods")
    val postingRestrictedToMods: kotlin.Boolean,

    @Json(name = "instance_id")
    val instanceId: java.math.BigDecimal,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "updated")
    val updated: kotlin.String? = null,

    @Json(name = "icon")
    val icon: kotlin.String? = null,

    @Json(name = "banner")
    val banner: kotlin.String? = null

)

