/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param creatorId 
 * @param commentId 
 * @param originalCommentText 
 * @param reason 
 * @param resolved 
 * @param published 
 * @param resolverId 
 * @param updated 
 */
@JsonClass(generateAdapter = true)

data class CommentReport (

    @Json(name = "id")
    val id: java.math.BigDecimal,

    @Json(name = "creator_id")
    val creatorId: java.math.BigDecimal,

    @Json(name = "comment_id")
    val commentId: java.math.BigDecimal,

    @Json(name = "original_comment_text")
    val originalCommentText: kotlin.String,

    @Json(name = "reason")
    val reason: kotlin.String,

    @Json(name = "resolved")
    val resolved: kotlin.Boolean,

    @Json(name = "published")
    val published: kotlin.String,

    @Json(name = "resolver_id")
    val resolverId: java.math.BigDecimal? = null,

    @Json(name = "updated")
    val updated: kotlin.String? = null

)

