/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param communityId 
 * @param subscribers 
 * @param posts 
 * @param comments 
 * @param published 
 * @param usersActiveDay 
 * @param usersActiveWeek 
 * @param usersActiveMonth 
 * @param usersActiveHalfYear 
 * @param hotRank 
 */
@JsonClass(generateAdapter = true)

data class CommunityAggregates (

    @Json(name = "id")
    val id: java.math.BigDecimal,

    @Json(name = "community_id")
    val communityId: java.math.BigDecimal,

    @Json(name = "subscribers")
    val subscribers: java.math.BigDecimal,

    @Json(name = "posts")
    val posts: java.math.BigDecimal,

    @Json(name = "comments")
    val comments: java.math.BigDecimal,

    @Json(name = "published")
    val published: kotlin.String,

    @Json(name = "users_active_day")
    val usersActiveDay: java.math.BigDecimal,

    @Json(name = "users_active_week")
    val usersActiveWeek: java.math.BigDecimal,

    @Json(name = "users_active_month")
    val usersActiveMonth: java.math.BigDecimal,

    @Json(name = "users_active_half_year")
    val usersActiveHalfYear: java.math.BigDecimal,

    @Json(name = "hot_rank")
    val hotRank: java.math.BigDecimal

)

