/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models

import com.neaniesoft.warami.api.models.CommentView

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param commentView 
 * @param recipientIds 
 * @param formId 
 */
@JsonClass(generateAdapter = true)

data class CommentResponse (

    @Json(name = "comment_view")
    val commentView: CommentView,

    @Json(name = "recipient_ids")
    val recipientIds: kotlin.collections.List<java.math.BigDecimal>,

    @Json(name = "form_id")
    val formId: kotlin.String? = null

)

