/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models

import com.neaniesoft.warami.api.models.Community
import com.neaniesoft.warami.api.models.CommunityAggregates
import com.neaniesoft.warami.api.models.SubscribedType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param community 
 * @param subscribed 
 * @param blocked 
 * @param counts 
 */
@JsonClass(generateAdapter = true)

data class CommunityView (

    @Json(name = "community")
    val community: Community,

    @Json(name = "subscribed")
    val subscribed: SubscribedType,

    @Json(name = "blocked")
    val blocked: kotlin.Boolean,

    @Json(name = "counts")
    val counts: CommunityAggregates

)

