/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param localSiteId 
 * @param shortcode 
 * @param imageUrl 
 * @param altText 
 * @param category 
 * @param published 
 * @param updated 
 */
@JsonClass(generateAdapter = true)

data class CustomEmoji (

    @Json(name = "id")
    val id: java.math.BigDecimal,

    @Json(name = "local_site_id")
    val localSiteId: java.math.BigDecimal,

    @Json(name = "shortcode")
    val shortcode: kotlin.String,

    @Json(name = "image_url")
    val imageUrl: kotlin.String,

    @Json(name = "alt_text")
    val altText: kotlin.String,

    @Json(name = "category")
    val category: kotlin.String,

    @Json(name = "published")
    val published: kotlin.String,

    @Json(name = "updated")
    val updated: kotlin.String? = null

)

