/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models

import com.neaniesoft.warami.api.models.CustomEmoji
import com.neaniesoft.warami.api.models.CustomEmojiKeyword

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param customEmoji 
 * @param keywords 
 */
@JsonClass(generateAdapter = true)

data class CustomEmojiView (

    @Json(name = "custom_emoji")
    val customEmoji: CustomEmoji,

    @Json(name = "keywords")
    val keywords: kotlin.collections.List<CustomEmojiKeyword>

)

