/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param communityId 
 * @param auth 
 * @param title 
 * @param description 
 * @param icon 
 * @param banner 
 * @param discussionLanguages 
 */
@JsonClass(generateAdapter = true)

data class EditCommunity (

    @Json(name = "community_id")
    val communityId: java.math.BigDecimal,

    @Json(name = "auth")
    val auth: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "icon")
    val icon: kotlin.String? = null,

    @Json(name = "banner")
    val banner: kotlin.String? = null,

    @Json(name = "discussion_languages")
    val discussionLanguages: kotlin.collections.List<java.math.BigDecimal>? = null

)

