/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param commentId 
 * @param auth 
 * @param content 
 * @param languageId 
 * @param formId 
 */
@JsonClass(generateAdapter = true)

data class EditComment (

    @Json(name = "comment_id")
    val commentId: java.math.BigDecimal,

    @Json(name = "auth")
    val auth: kotlin.String,

    @Json(name = "content")
    val content: kotlin.String? = null,

    @Json(name = "language_id")
    val languageId: java.math.BigDecimal? = null,

    @Json(name = "form_id")
    val formId: kotlin.String? = null

)

