/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param category 
 * @param imageUrl 
 * @param altText 
 * @param keywords 
 * @param auth 
 */
@JsonClass(generateAdapter = true)

data class EditCustomEmoji (

    @Json(name = "id")
    val id: java.math.BigDecimal,

    @Json(name = "category")
    val category: kotlin.String,

    @Json(name = "image_url")
    val imageUrl: kotlin.String,

    @Json(name = "alt_text")
    val altText: kotlin.String,

    @Json(name = "keywords")
    val keywords: kotlin.collections.List<kotlin.String>,

    @Json(name = "auth")
    val auth: kotlin.String

)

