/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param postId 
 * @param auth 
 * @param name 
 * @param url 
 * @param body 
 * @param languageId 
 */
@JsonClass(generateAdapter = true)

data class EditPost (

    @Json(name = "post_id")
    val postId: java.math.BigDecimal,

    @Json(name = "auth")
    val auth: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "url")
    val url: kotlin.String? = null,

    @Json(name = "body")
    val body: kotlin.String? = null,

    @Json(name = "language_id")
    val languageId: java.math.BigDecimal? = null

)

