/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models

import com.neaniesoft.warami.api.models.Instance

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param linked 
 * @param allowed 
 * @param blocked 
 */
@JsonClass(generateAdapter = true)

data class FederatedInstances (

    @Json(name = "linked")
    val linked: kotlin.collections.List<Instance>,

    @Json(name = "allowed")
    val allowed: kotlin.collections.List<Instance>,

    @Json(name = "blocked")
    val blocked: kotlin.collections.List<Instance>

)

