/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param personId 
 * @param username 
 * @param page 
 * @param limit 
 * @param communityId 
 * @param auth 
 */
@JsonClass(generateAdapter = true)

data class GetPersonDetails (

    @Json(name = "person_id")
    val personId: java.math.BigDecimal? = null,

    @Json(name = "username")
    val username: kotlin.String? = null,

    @Json(name = "page")
    val page: java.math.BigDecimal? = null,

    @Json(name = "limit")
    val limit: java.math.BigDecimal? = null,

    @Json(name = "community_id")
    val communityId: java.math.BigDecimal? = null,

    @Json(name = "auth")
    val auth: kotlin.String? = null

)

