/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models

import com.neaniesoft.warami.api.models.CommunityModeratorView
import com.neaniesoft.warami.api.models.CommunityView
import com.neaniesoft.warami.api.models.PostView

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param postView 
 * @param communityView 
 * @param moderators 
 * @param crossPosts 
 */
@JsonClass(generateAdapter = true)

data class GetPostResponse (

    @Json(name = "post_view")
    val postView: PostView,

    @Json(name = "community_view")
    val communityView: CommunityView,

    @Json(name = "moderators")
    val moderators: kotlin.collections.List<CommunityModeratorView>,

    @Json(name = "cross_posts")
    val crossPosts: kotlin.collections.List<PostView>

)

