/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models

import com.neaniesoft.warami.api.models.CustomEmojiView
import com.neaniesoft.warami.api.models.Language
import com.neaniesoft.warami.api.models.MyUserInfo
import com.neaniesoft.warami.api.models.PersonView
import com.neaniesoft.warami.api.models.SiteView
import com.neaniesoft.warami.api.models.Tagline

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param siteView 
 * @param admins 
 * @param version 
 * @param allLanguages 
 * @param discussionLanguages 
 * @param taglines 
 * @param customEmojis 
 * @param myUser 
 */
@JsonClass(generateAdapter = true)

data class GetSiteResponse (

    @Json(name = "site_view")
    val siteView: SiteView,

    @Json(name = "admins")
    val admins: kotlin.collections.List<PersonView>,

    @Json(name = "version")
    val version: kotlin.String,

    @Json(name = "all_languages")
    val allLanguages: kotlin.collections.List<Language>,

    @Json(name = "discussion_languages")
    val discussionLanguages: kotlin.collections.List<java.math.BigDecimal>,

    @Json(name = "taglines")
    val taglines: kotlin.collections.List<Tagline>,

    @Json(name = "custom_emojis")
    val customEmojis: kotlin.collections.List<CustomEmojiView>,

    @Json(name = "my_user")
    val myUser: MyUserInfo? = null

)

