/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param replies 
 * @param mentions 
 * @param privateMessages 
 */
@JsonClass(generateAdapter = true)

data class GetUnreadCountResponse (

    @Json(name = "replies")
    val replies: java.math.BigDecimal,

    @Json(name = "mentions")
    val mentions: java.math.BigDecimal,

    @Json(name = "private_messages")
    val privateMessages: java.math.BigDecimal

)

