/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param domain 
 * @param published 
 * @param updated 
 * @param software 
 * @param version 
 */
@JsonClass(generateAdapter = true)

data class Instance (

    @Json(name = "id")
    val id: java.math.BigDecimal,

    @Json(name = "domain")
    val domain: kotlin.String,

    @Json(name = "published")
    val published: kotlin.String,

    @Json(name = "updated")
    val updated: kotlin.String? = null,

    @Json(name = "software")
    val software: kotlin.String? = null,

    @Json(name = "version")
    val version: kotlin.String? = null

)

