/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param code 
 * @param name 
 */
@JsonClass(generateAdapter = true)

data class Language (

    @Json(name = "id")
    val id: java.math.BigDecimal,

    @Json(name = "code")
    val code: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String

)

