/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models

import com.neaniesoft.warami.api.models.PrivateMessageReportView

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param privateMessageReports 
 */
@JsonClass(generateAdapter = true)

data class ListPrivateMessageReportsResponse (

    @Json(name = "private_message_reports")
    val privateMessageReports: kotlin.collections.List<PrivateMessageReportView>

)

