/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param personId 
 * @param theme 
 * @param interfaceLanguage 
 * @param validatorTime 
 * @param email 
 * @param totp2faUrl 
 */
@JsonClass(generateAdapter = true)

data class LocalUser (

    @Json(name = "id")
    val id: java.math.BigDecimal,

    @Json(name = "person_id")
    val personId: java.math.BigDecimal,

    @Json(name = "theme")
    val theme: kotlin.String,

    @Json(name = "interface_language")
    val interfaceLanguage: kotlin.String,

    @Json(name = "validator_time")
    val validatorTime: kotlin.String,

    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "totp_2fa_url")
    val totp2faUrl: kotlin.String? = null

)

