/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param localSiteId 
 * @param message 
 * @param messagePerSecond 
 * @param post 
 * @param postPerSecond 
 * @param register 
 * @param registerPerSecond 
 * @param image 
 * @param imagePerSecond 
 * @param comment 
 * @param commentPerSecond 
 * @param search 
 * @param searchPerSecond 
 * @param published 
 * @param updated 
 */
@JsonClass(generateAdapter = true)

data class LocalSiteRateLimit (

    @Json(name = "id")
    val id: java.math.BigDecimal,

    @Json(name = "local_site_id")
    val localSiteId: java.math.BigDecimal,

    @Json(name = "message")
    val message: java.math.BigDecimal,

    @Json(name = "message_per_second")
    val messagePerSecond: java.math.BigDecimal,

    @Json(name = "post")
    val post: java.math.BigDecimal,

    @Json(name = "post_per_second")
    val postPerSecond: java.math.BigDecimal,

    @Json(name = "register")
    val register: java.math.BigDecimal,

    @Json(name = "register_per_second")
    val registerPerSecond: java.math.BigDecimal,

    @Json(name = "image")
    val image: java.math.BigDecimal,

    @Json(name = "image_per_second")
    val imagePerSecond: java.math.BigDecimal,

    @Json(name = "comment")
    val comment: java.math.BigDecimal,

    @Json(name = "comment_per_second")
    val commentPerSecond: java.math.BigDecimal,

    @Json(name = "search")
    val search: java.math.BigDecimal,

    @Json(name = "search_per_second")
    val searchPerSecond: java.math.BigDecimal,

    @Json(name = "published")
    val published: kotlin.String,

    @Json(name = "updated")
    val updated: kotlin.String? = null

)

