/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models

import com.neaniesoft.warami.api.models.LocalUser
import com.neaniesoft.warami.api.models.Person
import com.neaniesoft.warami.api.models.PersonAggregates

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param localUser 
 * @param person 
 * @param counts 
 */
@JsonClass(generateAdapter = true)

data class LocalUserView (

    @Json(name = "local_user")
    val localUser: LocalUser,

    @Json(name = "person")
    val person: Person,

    @Json(name = "counts")
    val counts: PersonAggregates

)

