/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param siteId 
 * @param defaultTheme 
 * @param actorNameMaxLength 
 * @param captchaDifficulty 
 * @param published 
 * @param applicationQuestion 
 * @param legalInformation 
 * @param slurFilterRegex 
 * @param updated 
 */
@JsonClass(generateAdapter = true)

data class LocalSite (

    @Json(name = "id")
    val id: java.math.BigDecimal,

    @Json(name = "site_id")
    val siteId: java.math.BigDecimal,

    @Json(name = "default_theme")
    val defaultTheme: kotlin.String,

    @Json(name = "actor_name_max_length")
    val actorNameMaxLength: java.math.BigDecimal,

    @Json(name = "captcha_difficulty")
    val captchaDifficulty: kotlin.String,

    @Json(name = "published")
    val published: kotlin.String,

    @Json(name = "application_question")
    val applicationQuestion: kotlin.String? = null,

    @Json(name = "legal_information")
    val legalInformation: kotlin.String? = null,

    @Json(name = "slur_filter_regex")
    val slurFilterRegex: kotlin.String? = null,

    @Json(name = "updated")
    val updated: kotlin.String? = null

)

