/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models

import com.neaniesoft.warami.api.models.ListingType
import com.neaniesoft.warami.api.models.SortType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param personId 
 * @param showNsfw 
 * @param theme 
 * @param defaultSortType 
 * @param defaultListingType 
 * @param interfaceLanguage 
 * @param showAvatars 
 * @param sendNotificationsToEmail 
 * @param validatorTime 
 * @param showScores 
 * @param showBotAccounts 
 * @param showReadPosts 
 * @param showNewPostNotifs 
 * @param emailVerified 
 * @param acceptedApplication 
 * @param email 
 * @param totp2faUrl 
 */
@JsonClass(generateAdapter = true)

data class LocalUser (

    @Json(name = "id")
    val id: java.math.BigDecimal,

    @Json(name = "person_id")
    val personId: java.math.BigDecimal,

    @Json(name = "show_nsfw")
    val showNsfw: kotlin.Boolean,

    @Json(name = "theme")
    val theme: kotlin.String,

    @Json(name = "default_sort_type")
    val defaultSortType: SortType,

    @Json(name = "default_listing_type")
    val defaultListingType: ListingType,

    @Json(name = "interface_language")
    val interfaceLanguage: kotlin.String,

    @Json(name = "show_avatars")
    val showAvatars: kotlin.Boolean,

    @Json(name = "send_notifications_to_email")
    val sendNotificationsToEmail: kotlin.Boolean,

    @Json(name = "validator_time")
    val validatorTime: kotlin.String,

    @Json(name = "show_scores")
    val showScores: kotlin.Boolean,

    @Json(name = "show_bot_accounts")
    val showBotAccounts: kotlin.Boolean,

    @Json(name = "show_read_posts")
    val showReadPosts: kotlin.Boolean,

    @Json(name = "show_new_post_notifs")
    val showNewPostNotifs: kotlin.Boolean,

    @Json(name = "email_verified")
    val emailVerified: kotlin.Boolean,

    @Json(name = "accepted_application")
    val acceptedApplication: kotlin.Boolean,

    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "totp_2fa_url")
    val totp2faUrl: kotlin.String? = null

)

