/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param usernameOrEmail 
 * @param password 
 * @param totp2faToken 
 */
@JsonClass(generateAdapter = true)

data class Login (

    @Json(name = "username_or_email")
    val usernameOrEmail: kotlin.String,

    @Json(name = "password")
    val password: kotlin.String,

    @Json(name = "totp_2fa_token")
    val totp2faToken: kotlin.String? = null

)

