/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models

import com.neaniesoft.warami.api.models.Community
import com.neaniesoft.warami.api.models.ModAddCommunity
import com.neaniesoft.warami.api.models.Person

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param modAddCommunity 
 * @param community 
 * @param moddedPerson 
 * @param moderator 
 */
@JsonClass(generateAdapter = true)

data class ModAddCommunityView (

    @Json(name = "mod_add_community")
    val modAddCommunity: ModAddCommunity,

    @Json(name = "community")
    val community: Community,

    @Json(name = "modded_person")
    val moddedPerson: Person,

    @Json(name = "moderator")
    val moderator: Person? = null

)

