/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models

import com.neaniesoft.warami.api.models.Community
import com.neaniesoft.warami.api.models.ModBanFromCommunity
import com.neaniesoft.warami.api.models.Person

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param modBanFromCommunity 
 * @param community 
 * @param bannedPerson 
 * @param moderator 
 */
@JsonClass(generateAdapter = true)

data class ModBanFromCommunityView (

    @Json(name = "mod_ban_from_community")
    val modBanFromCommunity: ModBanFromCommunity,

    @Json(name = "community")
    val community: Community,

    @Json(name = "banned_person")
    val bannedPerson: Person,

    @Json(name = "moderator")
    val moderator: Person? = null

)

