/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models

import com.neaniesoft.warami.api.models.ModBan
import com.neaniesoft.warami.api.models.Person

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param modBan 
 * @param bannedPerson 
 * @param moderator 
 */
@JsonClass(generateAdapter = true)

data class ModBanView (

    @Json(name = "mod_ban")
    val modBan: ModBan,

    @Json(name = "banned_person")
    val bannedPerson: Person,

    @Json(name = "moderator")
    val moderator: Person? = null

)

