/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models

import com.neaniesoft.warami.api.models.Community
import com.neaniesoft.warami.api.models.ModFeaturePost
import com.neaniesoft.warami.api.models.Person
import com.neaniesoft.warami.api.models.Post

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param modFeaturePost 
 * @param post 
 * @param community 
 * @param moderator 
 */
@JsonClass(generateAdapter = true)

data class ModFeaturePostView (

    @Json(name = "mod_feature_post")
    val modFeaturePost: ModFeaturePost,

    @Json(name = "post")
    val post: Post,

    @Json(name = "community")
    val community: Community,

    @Json(name = "moderator")
    val moderator: Person? = null

)

