/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models

import com.neaniesoft.warami.api.models.Community
import com.neaniesoft.warami.api.models.ModHideCommunity
import com.neaniesoft.warami.api.models.Person

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param modHideCommunity 
 * @param community 
 * @param admin 
 */
@JsonClass(generateAdapter = true)

data class ModHideCommunityView (

    @Json(name = "mod_hide_community")
    val modHideCommunity: ModHideCommunity,

    @Json(name = "community")
    val community: Community,

    @Json(name = "admin")
    val admin: Person? = null

)

