/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param modPersonId 
 * @param commentId 
 * @param `when` 
 * @param reason 
 */
@JsonClass(generateAdapter = true)

data class ModRemoveComment (

    @Json(name = "id")
    val id: java.math.BigDecimal,

    @Json(name = "mod_person_id")
    val modPersonId: java.math.BigDecimal,

    @Json(name = "comment_id")
    val commentId: java.math.BigDecimal,

    @Json(name = "when_")
    val `when`: kotlin.String,

    @Json(name = "reason")
    val reason: kotlin.String? = null

)

