/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models

import com.neaniesoft.warami.api.models.Comment
import com.neaniesoft.warami.api.models.Community
import com.neaniesoft.warami.api.models.ModRemoveComment
import com.neaniesoft.warami.api.models.Person
import com.neaniesoft.warami.api.models.Post

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param modRemoveComment 
 * @param comment 
 * @param commenter 
 * @param post 
 * @param community 
 * @param moderator 
 */
@JsonClass(generateAdapter = true)

data class ModRemoveCommentView (

    @Json(name = "mod_remove_comment")
    val modRemoveComment: ModRemoveComment,

    @Json(name = "comment")
    val comment: Comment,

    @Json(name = "commenter")
    val commenter: Person,

    @Json(name = "post")
    val post: Post,

    @Json(name = "community")
    val community: Community,

    @Json(name = "moderator")
    val moderator: Person? = null

)

