/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models

import com.neaniesoft.warami.api.models.CommunityBlockView
import com.neaniesoft.warami.api.models.CommunityFollowerView
import com.neaniesoft.warami.api.models.CommunityModeratorView
import com.neaniesoft.warami.api.models.LocalUserView
import com.neaniesoft.warami.api.models.PersonBlockView

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param localUserView 
 * @param follows 
 * @param moderates 
 * @param communityBlocks 
 * @param personBlocks 
 * @param discussionLanguages 
 */
@JsonClass(generateAdapter = true)

data class MyUserInfo (

    @Json(name = "local_user_view")
    val localUserView: LocalUserView,

    @Json(name = "follows")
    val follows: kotlin.collections.List<CommunityFollowerView>,

    @Json(name = "moderates")
    val moderates: kotlin.collections.List<CommunityModeratorView>,

    @Json(name = "community_blocks")
    val communityBlocks: kotlin.collections.List<CommunityBlockView>,

    @Json(name = "person_blocks")
    val personBlocks: kotlin.collections.List<PersonBlockView>,

    @Json(name = "discussion_languages")
    val discussionLanguages: kotlin.collections.List<java.math.BigDecimal>

)

