/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param token 
 * @param password 
 * @param passwordVerify 
 */
@JsonClass(generateAdapter = true)

data class PasswordChangeAfterReset (

    @Json(name = "token")
    val token: kotlin.String,

    @Json(name = "password")
    val password: kotlin.String,

    @Json(name = "password_verify")
    val passwordVerify: kotlin.String

)

