/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param name 
 * @param published 
 * @param actorId 
 * @param instanceId 
 * @param displayName 
 * @param avatar 
 * @param updated 
 * @param bio 
 * @param banner 
 * @param matrixUserId 
 * @param banExpires 
 */
@JsonClass(generateAdapter = true)

data class Person (

    @Json(name = "id")
    val id: java.math.BigDecimal,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "published")
    val published: kotlin.String,

    @Json(name = "actor_id")
    val actorId: kotlin.String,

    @Json(name = "instance_id")
    val instanceId: java.math.BigDecimal,

    @Json(name = "display_name")
    val displayName: kotlin.String? = null,

    @Json(name = "avatar")
    val avatar: kotlin.String? = null,

    @Json(name = "updated")
    val updated: kotlin.String? = null,

    @Json(name = "bio")
    val bio: kotlin.String? = null,

    @Json(name = "banner")
    val banner: kotlin.String? = null,

    @Json(name = "matrix_user_id")
    val matrixUserId: kotlin.String? = null,

    @Json(name = "ban_expires")
    val banExpires: kotlin.String? = null

)

