/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param personId 
 * @param postCount 
 * @param postScore 
 * @param commentCount 
 * @param commentScore 
 */
@JsonClass(generateAdapter = true)

data class PersonAggregates (

    @Json(name = "id")
    val id: java.math.BigDecimal,

    @Json(name = "person_id")
    val personId: java.math.BigDecimal,

    @Json(name = "post_count")
    val postCount: java.math.BigDecimal,

    @Json(name = "post_score")
    val postScore: java.math.BigDecimal,

    @Json(name = "comment_count")
    val commentCount: java.math.BigDecimal,

    @Json(name = "comment_score")
    val commentScore: java.math.BigDecimal

)

