/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models

import com.neaniesoft.warami.api.models.Community
import com.neaniesoft.warami.api.models.Person
import com.neaniesoft.warami.api.models.Post
import com.neaniesoft.warami.api.models.PostAggregates
import com.neaniesoft.warami.api.models.SubscribedType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param post 
 * @param creator 
 * @param community 
 * @param creatorBannedFromCommunity 
 * @param counts 
 * @param subscribed 
 * @param saved 
 * @param read 
 * @param creatorBlocked 
 * @param unreadComments 
 * @param myVote 
 */
@JsonClass(generateAdapter = true)

data class PostView (

    @Json(name = "post")
    val post: Post,

    @Json(name = "creator")
    val creator: Person,

    @Json(name = "community")
    val community: Community,

    @Json(name = "creator_banned_from_community")
    val creatorBannedFromCommunity: kotlin.Boolean,

    @Json(name = "counts")
    val counts: PostAggregates,

    @Json(name = "subscribed")
    val subscribed: SubscribedType,

    @Json(name = "saved")
    val saved: kotlin.Boolean,

    @Json(name = "read")
    val read: kotlin.Boolean,

    @Json(name = "creator_blocked")
    val creatorBlocked: kotlin.Boolean,

    @Json(name = "unread_comments")
    val unreadComments: java.math.BigDecimal,

    @Json(name = "my_vote")
    val myVote: java.math.BigDecimal? = null

)

