/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param name 
 * @param creatorId 
 * @param communityId 
 * @param removed 
 * @param locked 
 * @param published 
 * @param deleted 
 * @param nsfw 
 * @param apId 
 * @param local 
 * @param languageId 
 * @param featuredCommunity 
 * @param featuredLocal 
 * @param url 
 * @param body 
 * @param updated 
 * @param embedTitle 
 * @param embedDescription 
 * @param thumbnailUrl 
 * @param embedVideoUrl 
 */
@JsonClass(generateAdapter = true)

data class Post (

    @Json(name = "id")
    val id: java.math.BigDecimal,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "creator_id")
    val creatorId: java.math.BigDecimal,

    @Json(name = "community_id")
    val communityId: java.math.BigDecimal,

    @Json(name = "removed")
    val removed: kotlin.Boolean,

    @Json(name = "locked")
    val locked: kotlin.Boolean,

    @Json(name = "published")
    val published: kotlin.String,

    @Json(name = "deleted")
    val deleted: kotlin.Boolean,

    @Json(name = "nsfw")
    val nsfw: kotlin.Boolean,

    @Json(name = "ap_id")
    val apId: kotlin.String,

    @Json(name = "local")
    val local: kotlin.Boolean,

    @Json(name = "language_id")
    val languageId: java.math.BigDecimal,

    @Json(name = "featured_community")
    val featuredCommunity: kotlin.Boolean,

    @Json(name = "featured_local")
    val featuredLocal: kotlin.Boolean,

    @Json(name = "url")
    val url: kotlin.String? = null,

    @Json(name = "body")
    val body: kotlin.String? = null,

    @Json(name = "updated")
    val updated: kotlin.String? = null,

    @Json(name = "embed_title")
    val embedTitle: kotlin.String? = null,

    @Json(name = "embed_description")
    val embedDescription: kotlin.String? = null,

    @Json(name = "thumbnail_url")
    val thumbnailUrl: kotlin.String? = null,

    @Json(name = "embed_video_url")
    val embedVideoUrl: kotlin.String? = null

)

