/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param postId 
 * @param comments 
 * @param score 
 * @param upvotes 
 * @param downvotes 
 * @param published 
 * @param newestCommentTimeNecro 
 * @param newestCommentTime 
 * @param featuredCommunity 
 * @param featuredLocal 
 * @param hotRank 
 * @param hotRankActive 
 */
@JsonClass(generateAdapter = true)

data class PostAggregates (

    @Json(name = "id")
    val id: java.math.BigDecimal,

    @Json(name = "post_id")
    val postId: java.math.BigDecimal,

    @Json(name = "comments")
    val comments: java.math.BigDecimal,

    @Json(name = "score")
    val score: java.math.BigDecimal,

    @Json(name = "upvotes")
    val upvotes: java.math.BigDecimal,

    @Json(name = "downvotes")
    val downvotes: java.math.BigDecimal,

    @Json(name = "published")
    val published: kotlin.String,

    @Json(name = "newest_comment_time_necro")
    val newestCommentTimeNecro: kotlin.String,

    @Json(name = "newest_comment_time")
    val newestCommentTime: kotlin.String,

    @Json(name = "featured_community")
    val featuredCommunity: kotlin.Boolean,

    @Json(name = "featured_local")
    val featuredLocal: kotlin.Boolean,

    @Json(name = "hot_rank")
    val hotRank: java.math.BigDecimal,

    @Json(name = "hot_rank_active")
    val hotRankActive: java.math.BigDecimal

)

