/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models

import com.neaniesoft.warami.api.models.Person
import com.neaniesoft.warami.api.models.PrivateMessage

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param privateMessage 
 * @param creator 
 * @param recipient 
 */
@JsonClass(generateAdapter = true)

data class PrivateMessageView (

    @Json(name = "private_message")
    val privateMessage: PrivateMessage,

    @Json(name = "creator")
    val creator: Person,

    @Json(name = "recipient")
    val recipient: Person

)

