/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param creatorId 
 * @param recipientId 
 * @param content 
 * @param deleted 
 * @param read 
 * @param published 
 * @param apId 
 * @param local 
 * @param updated 
 */
@JsonClass(generateAdapter = true)

data class PrivateMessage (

    @Json(name = "id")
    val id: java.math.BigDecimal,

    @Json(name = "creator_id")
    val creatorId: java.math.BigDecimal,

    @Json(name = "recipient_id")
    val recipientId: java.math.BigDecimal,

    @Json(name = "content")
    val content: kotlin.String,

    @Json(name = "deleted")
    val deleted: kotlin.Boolean,

    @Json(name = "read")
    val read: kotlin.Boolean,

    @Json(name = "published")
    val published: kotlin.String,

    @Json(name = "ap_id")
    val apId: kotlin.String,

    @Json(name = "local")
    val local: kotlin.Boolean,

    @Json(name = "updated")
    val updated: kotlin.String? = null

)

