/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models

import com.neaniesoft.warami.api.models.PrivateMessageView

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param privateMessages 
 */
@JsonClass(generateAdapter = true)

data class PrivateMessagesResponse (

    @Json(name = "private_messages")
    val privateMessages: kotlin.collections.List<PrivateMessageView>

)

