/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: closed,requireApplication,`open`
 */

@JsonClass(generateAdapter = false)
enum class RegistrationMode(val value: kotlin.String) {

    @Json(name = "Closed")
    closed("Closed"),

    @Json(name = "RequireApplication")
    requireApplication("RequireApplication"),

    @Json(name = "Open")
    `open`("Open");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is RegistrationMode) "$data" else null

        /**
         * Returns a valid [RegistrationMode] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): RegistrationMode? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

