/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param username 
 * @param password 
 * @param passwordVerify 
 * @param email 
 * @param captchaUuid 
 * @param captchaAnswer 
 * @param honeypot 
 * @param answer 
 */
@JsonClass(generateAdapter = true)

data class Register (

    @Json(name = "username")
    val username: kotlin.String,

    @Json(name = "password")
    val password: kotlin.String,

    @Json(name = "password_verify")
    val passwordVerify: kotlin.String,

    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "captcha_uuid")
    val captchaUuid: kotlin.String? = null,

    @Json(name = "captcha_answer")
    val captchaAnswer: kotlin.String? = null,

    @Json(name = "honeypot")
    val honeypot: kotlin.String? = null,

    @Json(name = "answer")
    val answer: kotlin.String? = null

)

