/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param localUserId 
 * @param answer 
 * @param published 
 * @param adminId 
 * @param denyReason 
 */
@JsonClass(generateAdapter = true)

data class RegistrationApplication (

    @Json(name = "id")
    val id: java.math.BigDecimal,

    @Json(name = "local_user_id")
    val localUserId: java.math.BigDecimal,

    @Json(name = "answer")
    val answer: kotlin.String,

    @Json(name = "published")
    val published: kotlin.String,

    @Json(name = "admin_id")
    val adminId: java.math.BigDecimal? = null,

    @Json(name = "deny_reason")
    val denyReason: kotlin.String? = null

)

