/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models

import com.neaniesoft.warami.api.models.CommentView
import com.neaniesoft.warami.api.models.CommunityView
import com.neaniesoft.warami.api.models.PersonView
import com.neaniesoft.warami.api.models.PostView

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param comment 
 * @param post 
 * @param community 
 * @param person 
 */
@JsonClass(generateAdapter = true)

data class ResolveObjectResponse (

    @Json(name = "comment")
    val comment: CommentView? = null,

    @Json(name = "post")
    val post: PostView? = null,

    @Json(name = "community")
    val community: CommunityView? = null,

    @Json(name = "person")
    val person: PersonView? = null

)

