/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models

import com.neaniesoft.warami.api.models.ListingType
import com.neaniesoft.warami.api.models.SortType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param auth 
 * @param showNsfw 
 * @param showScores 
 * @param theme 
 * @param defaultSortType 
 * @param defaultListingType 
 * @param interfaceLanguage 
 * @param avatar 
 * @param banner 
 * @param displayName 
 * @param email 
 * @param bio 
 * @param matrixUserId 
 * @param showAvatars 
 * @param sendNotificationsToEmail 
 * @param botAccount 
 * @param showBotAccounts 
 * @param showReadPosts 
 * @param showNewPostNotifs 
 * @param discussionLanguages 
 * @param generateTotp2fa 
 */
@JsonClass(generateAdapter = true)

data class SaveUserSettings (

    @Json(name = "auth")
    val auth: kotlin.String,

    @Json(name = "show_nsfw")
    val showNsfw: kotlin.Boolean? = null,

    @Json(name = "show_scores")
    val showScores: kotlin.Boolean? = null,

    @Json(name = "theme")
    val theme: kotlin.String? = null,

    @Json(name = "default_sort_type")
    val defaultSortType: SortType? = null,

    @Json(name = "default_listing_type")
    val defaultListingType: ListingType? = null,

    @Json(name = "interface_language")
    val interfaceLanguage: kotlin.String? = null,

    @Json(name = "avatar")
    val avatar: kotlin.String? = null,

    @Json(name = "banner")
    val banner: kotlin.String? = null,

    @Json(name = "display_name")
    val displayName: kotlin.String? = null,

    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "bio")
    val bio: kotlin.String? = null,

    @Json(name = "matrix_user_id")
    val matrixUserId: kotlin.String? = null,

    @Json(name = "show_avatars")
    val showAvatars: kotlin.Boolean? = null,

    @Json(name = "send_notifications_to_email")
    val sendNotificationsToEmail: kotlin.Boolean? = null,

    @Json(name = "bot_account")
    val botAccount: kotlin.Boolean? = null,

    @Json(name = "show_bot_accounts")
    val showBotAccounts: kotlin.Boolean? = null,

    @Json(name = "show_read_posts")
    val showReadPosts: kotlin.Boolean? = null,

    @Json(name = "show_new_post_notifs")
    val showNewPostNotifs: kotlin.Boolean? = null,

    @Json(name = "discussion_languages")
    val discussionLanguages: kotlin.collections.List<java.math.BigDecimal>? = null,

    @Json(name = "generate_totp_2fa")
    val generateTotp2fa: kotlin.Boolean? = null

)

