/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param auth 
 * @param theme 
 * @param interfaceLanguage 
 * @param avatar 
 * @param banner 
 * @param displayName 
 * @param email 
 * @param bio 
 * @param matrixUserId 
 * @param discussionLanguages 
 */
@JsonClass(generateAdapter = true)

data class SaveUserSettings (

    @Json(name = "auth")
    val auth: kotlin.String,

    @Json(name = "theme")
    val theme: kotlin.String? = null,

    @Json(name = "interface_language")
    val interfaceLanguage: kotlin.String? = null,

    @Json(name = "avatar")
    val avatar: kotlin.String? = null,

    @Json(name = "banner")
    val banner: kotlin.String? = null,

    @Json(name = "display_name")
    val displayName: kotlin.String? = null,

    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "bio")
    val bio: kotlin.String? = null,

    @Json(name = "matrix_user_id")
    val matrixUserId: kotlin.String? = null,

    @Json(name = "discussion_languages")
    val discussionLanguages: kotlin.collections.List<java.math.BigDecimal>? = null

)

