/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models

import com.neaniesoft.warami.api.models.ListingType
import com.neaniesoft.warami.api.models.SearchType
import com.neaniesoft.warami.api.models.SortType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param q 
 * @param communityId 
 * @param communityName 
 * @param creatorId 
 * @param type 
 * @param sort 
 * @param listingType 
 * @param page 
 * @param limit 
 * @param auth 
 */
@JsonClass(generateAdapter = true)

data class Search (

    @Json(name = "q")
    val q: kotlin.String,

    @Json(name = "community_id")
    val communityId: java.math.BigDecimal? = null,

    @Json(name = "community_name")
    val communityName: kotlin.String? = null,

    @Json(name = "creator_id")
    val creatorId: java.math.BigDecimal? = null,

    @Json(name = "type_")
    val type: SearchType? = null,

    @Json(name = "sort")
    val sort: SortType? = null,

    @Json(name = "listing_type")
    val listingType: ListingType? = null,

    @Json(name = "page")
    val page: java.math.BigDecimal? = null,

    @Json(name = "limit")
    val limit: java.math.BigDecimal? = null,

    @Json(name = "auth")
    val auth: kotlin.String? = null

)

