/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models

import com.neaniesoft.warami.api.models.SiteView
import com.neaniesoft.warami.api.models.Tagline

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param siteView 
 * @param taglines 
 */
@JsonClass(generateAdapter = true)

data class SiteResponse (

    @Json(name = "site_view")
    val siteView: SiteView,

    @Json(name = "taglines")
    val taglines: kotlin.collections.List<Tagline>

)

