/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param siteId 
 * @param users 
 * @param posts 
 * @param comments 
 * @param communities 
 * @param usersActiveDay 
 * @param usersActiveWeek 
 * @param usersActiveMonth 
 * @param usersActiveHalfYear 
 */
@JsonClass(generateAdapter = true)

data class SiteAggregates (

    @Json(name = "id")
    val id: java.math.BigDecimal,

    @Json(name = "site_id")
    val siteId: java.math.BigDecimal,

    @Json(name = "users")
    val users: java.math.BigDecimal,

    @Json(name = "posts")
    val posts: java.math.BigDecimal,

    @Json(name = "comments")
    val comments: java.math.BigDecimal,

    @Json(name = "communities")
    val communities: java.math.BigDecimal,

    @Json(name = "users_active_day")
    val usersActiveDay: java.math.BigDecimal,

    @Json(name = "users_active_week")
    val usersActiveWeek: java.math.BigDecimal,

    @Json(name = "users_active_month")
    val usersActiveMonth: java.math.BigDecimal,

    @Json(name = "users_active_half_year")
    val usersActiveHalfYear: java.math.BigDecimal

)

