/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models

import com.neaniesoft.warami.api.models.LocalSite
import com.neaniesoft.warami.api.models.LocalSiteRateLimit
import com.neaniesoft.warami.api.models.Site
import com.neaniesoft.warami.api.models.SiteAggregates

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param site 
 * @param localSite 
 * @param localSiteRateLimit 
 * @param counts 
 */
@JsonClass(generateAdapter = true)

data class SiteView (

    @Json(name = "site")
    val site: Site,

    @Json(name = "local_site")
    val localSite: LocalSite,

    @Json(name = "local_site_rate_limit")
    val localSiteRateLimit: LocalSiteRateLimit,

    @Json(name = "counts")
    val counts: SiteAggregates

)

