/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: hot,new,old,active,topDay,topWeek,topMonth,topYear,topAll,mostComments,newComments,topHour,topSixHour,topTwelveHour,topThreeMonths,topSixMonths,topNineMonths
 */

@JsonClass(generateAdapter = false)
enum class SortType(val value: kotlin.String) {

    @Json(name = "Hot")
    hot("Hot"),

    @Json(name = "New")
    new("New"),

    @Json(name = "Old")
    old("Old"),

    @Json(name = "Active")
    active("Active"),

    @Json(name = "TopDay")
    topDay("TopDay"),

    @Json(name = "TopWeek")
    topWeek("TopWeek"),

    @Json(name = "TopMonth")
    topMonth("TopMonth"),

    @Json(name = "TopYear")
    topYear("TopYear"),

    @Json(name = "TopAll")
    topAll("TopAll"),

    @Json(name = "MostComments")
    mostComments("MostComments"),

    @Json(name = "NewComments")
    newComments("NewComments"),

    @Json(name = "TopHour")
    topHour("TopHour"),

    @Json(name = "TopSixHour")
    topSixHour("TopSixHour"),

    @Json(name = "TopTwelveHour")
    topTwelveHour("TopTwelveHour"),

    @Json(name = "TopThreeMonths")
    topThreeMonths("TopThreeMonths"),

    @Json(name = "TopSixMonths")
    topSixMonths("TopSixMonths"),

    @Json(name = "TopNineMonths")
    topNineMonths("TopNineMonths");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is SortType) "$data" else null

        /**
         * Returns a valid [SortType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): SortType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

