/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.neaniesoft.warami.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param localSiteId 
 * @param content 
 * @param published 
 * @param updated 
 */
@JsonClass(generateAdapter = true)

data class Tagline (

    @Json(name = "id")
    val id: java.math.BigDecimal,

    @Json(name = "local_site_id")
    val localSiteId: java.math.BigDecimal,

    @Json(name = "content")
    val content: kotlin.String,

    @Json(name = "published")
    val published: kotlin.String,

    @Json(name = "updated")
    val updated: kotlin.String? = null

)

